name: A Little Spot in Baja
favicon: null
layout_spectrum: 0.7330238500144333
typography_spectrum: 0.6233775571454316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9952252709772438
  lightness: 0.9019328157883137
  saturation: 0.27658815239556134
  rhythmicContrast: 0.21264454256743193
purpose: []
